[versions]
lombok = "1.18.34"
spring = "3.3.5"
postgresql = "42.5.0"
liquibase = "4.30.0"
hibernate = "6.6.2.Final"

[libraries]
spring-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring" }
spring-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "spring" }
spring-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "spring" }
hibernate = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
liquibase = { module = "org.liquibase:liquibase-core", version.ref = "liquibase" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

[plugins]
spring = { id = "org.springframework.boot", version.ref = "spring" }

[bundles]
data-service = ["spring-starter", "spring-web", "spring-jpa", "postgresql", "liquibase"]
