server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: auction-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/auction
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog.xml
    enabled: true